#!/usr/bin/env bash
# displays "Best school" 10 times using while loop.

for file in *; do
    # Check if the file is not hidden and has a dash in its name
    if [[ ! $file == .* && $file == *-* ]]; then
        # Extract the part of the name after the first dash
        name="${file#*-}"
        # Print the extracted name
        echo "$name"
    fi
done
